# --- Параметры окна ---
width: 1300
height: 900
full_screen: 0

# --- Настройки графики ---
# Степень затемнения (0 - отключено, 255 - предел)
darkening_degree: 1
# Прозрачность хвостов (0 - отключено)
darkening_tail: 2
# Разнообразие цветов клана (от 0 (больше) до 255 (меньше))
color_threshold: 200
# Преимущество при выборе цвета (по массиву будет использован random.choice)
color_choice: [ r, g, b, gb ]

# --- Настройки симуляции ---
# Физика столкновений
enable_physics: 0
# Время жизни клетки
lifetime: 1000
# Ограничение числа клеток в клане
limit_clan_members: 100
# Процент выбора клетки повернуть налево
chance_turn_left: 8
# Процент выбора клетки повернуть направо
chance_turn_right: 8
# Процент выбора клетки повернуть в сторону точки клана
chance_turn_course: 5
# Процент деления клетки с мутацией
chance_divinity: 1
# Коэффициент деления клеток
ratio_divinity: 1
